export const TICKET_PRICE = 100; // BDT
export const SEATS_PER_BUS = 50;

export const ROUTE_DATA = [
  {
    routeNumber: 1,
    routeName: 'Dhanmondi – UIU',
    routeCode: 'DMD',
    stops: [
      'Zigatola Bus Stop',
      'Dhanmondi Keari Plaza',
      'Shankar Bus Stop',
      'Mohammadpur BRTC Bus Stop',
      'Manik Mia Avenue',
      'BARC, Farmgate',
      'Kakoli',
      'Gulshan 2',
      'Notun Bazar',
      'UIU',
    ],
    totalBuses: 6,
    seatsPerBus: 50,
    totalSeats: 300,
    remarks: 'No stoppage between Farmgate to Kakoli. Vehicles will ply through Elevated Expressway while returning from UIU.',
  },
  {
    routeNumber: 2,
    routeName: 'Palashi – UIU',
    routeCode: 'PALASHI',
    stops: [
      'Palashi',
      'Azimpur',
      'Dhaka College',
      'City College',
      'West Kalabagan',
      'Panthapath',
      'BARC, Farmgate',
      'Kakoli',
      'Gulshan 2',
      'Notun Bazar',
      'UIU',
    ],
    totalBuses: 3,
    seatsPerBus: 50,
    totalSeats: 150,
    remarks: 'No stoppage between Farmgate to Kakoli. Vehicles will ply through Elevated Expressway while returning from UIU.',
  },
  {
    routeNumber: 3,
    routeName: 'Mirpur – UIU',
    routeCode: 'MIRPUR',
    stops: [
      'Technical',
      'Mirpur 1',
      'Mirpur 2',
      'Mirpur 10',
      'Mirpur 11',
      'Mirpur 12',
      'ECB Chattar (Kalshi)',
      'Kuril Flyover',
      'Notun Bazar',
      'UIU',
    ],
    totalBuses: 3,
    seatsPerBus: 50,
    totalSeats: 150,
    remarks: '',
  },
  {
    routeNumber: 4,
    routeName: 'Signboard – UIU',
    routeCode: 'SIGN',
    stops: [
      'Signboard Mor',
      'Hanif Flyover',
      'Manik Nagar',
      'Mugdapara',
      'Bashabo',
      'Khilgaon Police Fari',
      'Abul Hotel',
      'Rampura Bridge',
      'Aftab Nagar',
      'Notun Bazar',
      'UIU',
    ],
    totalBuses: 3,
    seatsPerBus: 50,
    totalSeats: 150,
    remarks: '',
  },
  {
    routeNumber: 5,
    routeName: 'Jatrabari – UIU',
    routeCode: 'JBARI',
    stops: [
      'Jatrabari Mor',
      'Manik Nagar',
      'Mugdapara',
      'Bashabo',
      'Khilgaon Police Fari',
      'Abul Hotel',
      'Rampura Bridge',
      'Aftab Nagar',
      'Sunvally',
      'Notun Bazar',
      'UIU',
    ],
    totalBuses: 2,
    seatsPerBus: 50,
    totalSeats: 100,
    remarks: '',
  },
  {
    routeNumber: 6,
    routeName: 'Uttara – UIU',
    routeCode: 'UTTARA',
    stops: [
      'Abdullahpur',
      'House Building',
      'Azampur',
      'Jashimuddin',
      'Airport',
      'Khilkhet',
      'Kuril Flyover',
      '300 ft',
      'Bashundhara',
      'UIU',
    ],
    totalBuses: 1,
    seatsPerBus: 50,
    totalSeats: 50,
    remarks: '',
  },
] as const;

export const PAYMENT_METHODS = [
  { id: 'BKASH', name: 'bKash', icon: '📱', color: '#E2136E', description: 'Pay via bKash mobile banking' },
  { id: 'NAGAD', name: 'Nagad', icon: '📲', color: '#F6921E', description: 'Pay via Nagad digital financial service' },
  { id: 'ROCKET', name: 'Rocket', icon: '🚀', color: '#8B2F87', description: 'Pay via Rocket by Dutch-Bangla Bank' },
  { id: 'BANKING', name: 'Bank Transfer', icon: '🏦', color: '#1E3A5F', description: 'Pay via bank transfer' },
  { id: 'UCAM', name: 'UCAM Balance', icon: '🎓', color: '#F37021', description: 'Pay from your UIU campus account' },
] as const;

export const ROUTE_COLORS: Record<string, string> = {
  DMD: '#F37021',
  PALASHI: '#E91E63',
  MIRPUR: '#2196F3',
  SIGN: '#4CAF50',
  JBARI: '#9C27B0',
  UTTARA: '#FF9800',
};

export const DAYS_OFF = [4, 5]; // Thursday = 4, Friday = 5 in JS (0=Sunday)
